/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 17 07:53:30 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.ListNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ListNode_ESTest extends ListNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object object0 = new Object();
      ListNode listNode0 = new ListNode(object0);
      ListNode listNode1 = new ListNode((Object) "", listNode0);
      assertFalse(listNode1.equals((Object)listNode0));
  }
}
